apiVersion: apps/v1
kind: Deployment
metadata:
  name: buggy-app-frontend
  labels:
    app.kubernetes.io/name: buggy-app-frontend
    app.kubernetes.io/component: frontend
  annotations:
    hint: |
      Tell the frontend deployment how to reach the backend service by setting the
      environment variable BACKEND_ADDR.
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: buggy-app-frontend
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: buggy-app-frontend
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: "buggy-app-frontend"
        image: "ghcr.io/hayk96/buggy-app-challenge-frontend:v0.1.0"
        ports:
          - name: http
            containerPort: 3000
        securityContext:
          readOnlyRootFilesystem: true
        readinessProbe:
          initialDelaySeconds: 300
          periodSeconds: 10
          httpGet:
            port: http
            path: /healthy
